markdown: kramdown
highlighter: rouge
plugins: [jekyll-feed]
url: http://motftp.lab9k.gent/
title: 'Museum of Things for the People'
description: 'Get your latest info about Museum of Things for the People.'
author: Jefwillems
